---
version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - heimdall_data:/config
    ports:
      - ${PORT}:80
      - 443:443
    restart: unless-stopped
volumes:
  heimdall_data:
