---
version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
  portainer:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.home.local
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data: