---
version: "3"
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - homeassistant_data:/config
    restart: unless-stopped
volumes:
  homeassistant_data: