---
version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8002:80/tcp"
    environment:
      - TZ
      - WEBPASSWORD
    volumes:
      - pihole_data:/etc/pihole
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes:
  pihole_data: