---
version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-grafana_data:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - prometheus-grafana_data:/etc/grafana/grafana.ini
      - prometheus-grafana_data:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
      - prometheus
volumes:
  prometheus-grafana_data: