---
version: "3"
services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
