---
version: "3"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    volumes:
      - adguard_data/work:/opt/adguard/work
      - adguard_data/config:/opt/adguard/config
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/tcp"
      - "67:67/udp"
      - "8003:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3003:3000/tcp"
    restart: unless-stopped
volumes:
  adguard_data:
