---
version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/ssl/
    restart: unless-stopped