---
version: '3.4'

services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    environment:
      - EULA
      - SERVER_NAME
      - GAMEMODE
      - DIFFICULTY
      - VERSION
    ports:
      - 19132:19132/udp
    volumes:
      - minecraft-data:/data
    stdin_open: true
    tty: true

volumes:
  minecraft-data:
